#! /bin/bash

#Author: Praveen K R
#Date: 04/November/2019

#Parameters
#real_epsilonr=-1.0
#imag_epsilonr=-0.5

#Compilation
g++ -o main.o main.cpp

#Execution
for imag_epsilonr in  $(seq -0.1 -0.1 -0.5)
do
for real_epsilonr in $(seq 5.0 -0.001 -5.0) 
do
echo $real_epsilonr > inputfile
echo $imag_epsilonr >> inputfile
./main.o < inputfile >> 'outputfile_imagninary_epsilon'$imag_epsilonr

rm inputfile
done
done

#Cleaning
#rm inputfile
rm *.o
