#!/bin/bash  

echo "Beginning of the parameter definition phase"

# parameters

  outfilename=outputfile

  mu_r=1.0
for epsilon_r in  1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0
do
  for zeta in 1e-4 2e-4 2.5e-4 3e-4 3.5e-4 3.7e-4 3.8e-4 4e-4 6e-4 8e-4 1e-3 1.1e-3 1.2e-3 1.3e-3 1.4e-3 1.5e-3 1.6e-3
  do

  echo $zeta > inputfile
  echo $epsilon_r >> inputfile
  echo $mu_r >> inputfile

#echo "Execution phase"

g++ -lm -Wall -o main.o main.cpp
./main.o < inputfile  >> $outfilename'_epsilon_r_'$epsilon_r

#cleaning 
rm inputfile
rm *.o
 done
 done

echo "Simulation complete"
