#!/bin/bash  

echo "Beginning of the parameter definition phase"

# parameters

  outfilename=outputfile

  mu_r=1.0
for epsilon_r in $(seq 1.0 0.1 100) 
do

  echo $epsilon_r >> inputfile
  echo $mu_r >> inputfile

#echo "Execution phase"

g++ -lm -Wall -o main.o main.cpp
./main.o < inputfile  >> $outfilename

#cleaning 
rm inputfile
rm *.o
 done

echo "Simulation complete"
