#!/bin/bash  

echo "Beginning of the parameter definition phase"

# parameters

  outfilename=outputfile

  mu_r=1.0
#for epsilon_r in  1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0
for epsilon_r in $(seq 1.0 0.1 10) 
do

  echo $epsilon_r >> inputfile
  echo $mu_r >> inputfile

#echo "Execution phase"

g++ -lm -Wall -o main.o main.cpp
./main.o < inputfile  >> $outfilename

#cleaning 
rm inputfile
rm *.o
 done

echo "Simulation complete"
