#!/bin/bash  

echo "Beginning of the parameter definition phase"

# parameters

  outfilename=outputfile

  mu_r=1.0
  epsilon_r=1.0
#for epsilon_r in  1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0
#do
  for kappa in 1e-4 2e-4 2.5e-4 2.55e-4 2.6e-4 2.65e-4 2.7e-4 2.71e-4 2.72e-4 2.73e-4 2.74e-4 2.75e-4 2.8e-4 2.85e-4 2.9e-4 2.95e-4 3e-4 
  do

  echo $kappa > inputfile
  echo $epsilon_r >> inputfile
  echo $mu_r >> inputfile

#echo "Execution phase"

g++ -lm -Wall -o main.o main.cpp
./main.o < inputfile  >> $outfilename'_epsilon_r_'$epsilon_r

#cleaning 
rm inputfile
rm *.o
 #done
 done

echo "Simulation complete"
